---
- name: Assurer qu'AIDE est installé
  ansible.builtin.yum:
    name: aide
    state: present
  # Assurer que le paquet aide est installé

- name: Initialiser la base de données AIDE
  ansible.builtin.command:
    cmd: aide --init
    creates: /var/lib/aide/aide.db.gz
  # Initialiser la base de données aide si elle n'existe pas encore

- name: Déplacer la base de données AIDE initiale à son emplacement correct
  ansible.builtin.command:
    cmd: mv /var/lib/aide/aide.db.new.gz /var/lib/aide/aide.db.gz
    creates: /var/lib/aide/aide.db.gz
  # Déplacer la base de données initiale d'aide au bon emplacement après l'initialisation

- name: Créer le répertoire de configuration AIDE
  ansible.builtin.file:
    path: /etc/aide
    state: directory
    mode: '0755'
  # Créer le répertoire de configuration aide

- name: Assurer l'existence du fichier de configuration AIDE
  ansible.builtin.copy:
    dest: /etc/aide/aide.conf
    content: |
      # AIDE configuration file
      database = /var/lib/aide/aide.db.gz
      database_out = /var/lib/aide/aide.db.new.gz
      logfile = /var/log/aide/aide.log
      # Define the directories and files to monitor
      /bin    p+i+n+u+g+s+b+m+c+e+M+S+L+X
      /sbin   p+i+n+u+g+s+b+m+c+e+M+S+L+X
      /usr/bin p+i+n+u+g+s+b+m+c+e+M+S+L+X
      /usr/sbin p+i+n+u+g+s+b+m+c+e+M+S+L+X
      /etc    p+i+n+u+g+s+b+m+c+e+M+S+L+X
      /var/log p+i+n+u+g+s+b+m+c+e+M+S+L+X
    mode: '0644'
  # Assurer que le fichier de configuration aide existe avec des paramètres de surveillance pour les fichiers et répertoires critiques

- name: Créer un répertoire pour les journaux AIDE
  ansible.builtin.file:
    path: /var/log/aide
    state: directory
    mode: '0755'
  # Créer un répertoire pour stocker les journaux d'aide

- name: Configurer une tâche cron pour AIDE
  ansible.builtin.cron:
    name: "Exécuter AIDE quotidiennement"
    minute: "0"
    hour: "3"
    job: "/usr/sbin/aide --check >> /var/log/aide/aide.log 2>&1"
    state: present
  # Assurer que la tâche cron d'aide est configurée
