---

- name: Assurez-vous que aide est installer.
  ansible.builtin.yum:
    name: aide
    state: present
  # Assure que le paquet aide est installer

- name: Initialisez la base de données de aide
  ansible.builtin.command:
    cmd: aide --init
    creates: /var/lib/aide/aide.db.gz
  # Initialise la base de données aide si elle n'existe pas encore

- name: Déplacez la base de données initiale aide vers son emplacement approprié
  ansible.builtin.command:
    cmd: mv /var/lib/aide/aide.db.new.gz /var/lib/aide/aide.db.gz
    creates: /var/lib/aide/aide.db.gz
  # Déplace la base de données initiale d'aide au bon emplacement après l'initialisation

- name: Créez le répertoire de configuration aide
  ansible.builtin.file:
    path: /etc/aide
    state: directory
    mode: '0755'
- name: Assurez-vous que le fichier de configuration aide existe.
  ansible.builtin.copy:
    dest: /etc/aide/aide.conf
    content: |
      # AIDE configuration file
      database = /var/lib/aide/aide.db.gz
      database_out = /var/lib/aide/aide.db.new.gz
      logfile = /var/log/aide/aide.log
      # Define the directories and files to monitor
      /bin    p+i+n+u+g+s+b+m+c+e+M+S+L+X
      /sbin   p+i+n+u+g+s+b+m+c+e+M+S+L+X
      /usr/bin p+i+n+u+g+s+b+m+c+e+M+S+L+X
      /usr/sbin p+i+n+u+g+s+b+m+c+e+M+S+L+X
      /etc    p+i+n+u+g+s+b+m+c+e+M+S+L+X
      /var/log p+i+n+u+g+s+b+m+c+e+M+S+L+X
    mode: '0644'
  # Crée le fichier de configuration aide avec des paramètres de surveillance pour les fichiers et répertoires critiques

- name: Créez le répertoire pour les journaux aide
  ansible.builtin.file:
    path: /var/log/aide
    state: directory
    mode: '0755'
  # Crée un répertoire pour stocker les journaux d'aide

- name: Assurez-vous que la tâche cron aide est configurée.
  ansible.builtin.cron:
    name: "Run AIDE daily"
    minute: "0"
    hour: "3"
    job: "/usr/sbin/aide --check >> /var/log/aide/aide.log 2>&1"
    state: present
  become: yes

  # Configure une tâche cron pour exécuter aide tous les jours à 3h du matin et enregistrer les résultats dans les journaux
