---
- name: Assure que le paquet audit est installé
  ansible.builtin.yum:
    name: audit
    state: present


- name: Démarre et active le service auditd
  ansible.builtin.systemd:
    name: auditd
    enabled: yes
    state: started


- name: Configure la taille maximale du fichier journal
  ansible.builtin.lineinfile:
    path: /etc/audit/auditd.conf
    regexp: '^max_log_file'
    line: 'max_log_file = 50'

