---
- name: S'assurer que SELinux est en mode enforcing
  ansible.builtin.lineinfile:
    path: /etc/selinux/config
    regexp: '^SELINUX='
    line: 'SELINUX=enforcing'
  # Définit SELinux en mode enforcing

- name: Appliquer la politique SELinux
  ansible.builtin.command:
    cmd: setenforce 1
  # Applique immédiatement la politique SELinux
