---

- name: S'assurer que le service chronyd est désactivé
  ansible.builtin.systemd:
    name: chronyd
    enabled: no
    state: stopped
  # Désactive le service chronyd, qui est un serveur NTP

- name: S'assurer que le service CUPS est désactivé
  ansible.builtin.systemd:
    name: cups
    enabled: no
    state: stopped
  # Désactive le service CUPS (impression), si non nécessaire
