---

- name: S'assurer que la connexion root via SSH est désactivée
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^PermitRootLogin'
    line: 'PermitRootLogin no'
  # Désactive la connexion root via SSH

- name: S'assurer que l'authentification par mot de passe SSH est désactivée
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^PasswordAuthentication'
    line: 'PasswordAuthentication no'
  # Désactive l'authentification par mot de passe SSH
